version: '3.8'

services:
  organization:
    build:
      context: .
      dockerfile: apps/organization/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
    networks:
      - organi-network

  evaluation:
    build:
      context: .
      dockerfile: apps/evaluation/Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
    networks:
      - organi-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - organization
      - evaluation
    networks:
      - organi-network

networks:
  organi-network:
    driver: bridge